name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: grokify/.github/.github/workflows/ts-lint-pnpm.yaml@v0.4.0
    with:
      node-version: '20.x'
      pnpm-version: '9'
      lint-script: 'lint'
      format-check-script: 'format:check'

  ci:
    name: CI
    uses: grokify/.github/.github/workflows/ts-ci-pnpm.yaml@v0.4.0
    with:
      node-versions: '["20.x"]'
      pnpm-version: '9'
      test-script: 'test'
      build-script: 'build'
      typecheck-script: 'typecheck'
